title: Minimal theme
logo: /assets/img/BallRun.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
