title: BallRun
logo: /assets/img/BallRun.png
description: BallRun is a video game project.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
