title: BallRun
logo: /assets/img/BallRun.png
description: BallRun is an exciting and addictive mobile game that puts your skills to the test. In this thrilling adventure, you control a vibrant ball rolling through a dynamic and challenging world filled with obstacles, traps, and rewards
google_analytics:
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
