title: BallRun
logo: /assets/img/BallRun.png
description:
google_analytics:
theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
